#!/usr/bin/env bash
echo ""
echo -e "\033[1mDevOps Sandbox — Quick Reference\033[0m"
echo -e "\033[90m(Real k3s cluster — commands hit real Kubernetes)\033[0m"
echo ""
echo -e "\033[36mKubernetes:\033[0m"
echo "  k9s                                          # interactive cluster UI (q to quit)"
echo "  kubectl get pods -A                          # all pods"
echo "  kubectl get pods -n default -o wide"
echo "  kubectl logs deploy/web-app -f"
echo "  kubectl describe pod <name>"
echo "  kubectl get events -n default --sort-by=.lastTimestamp"
echo "  kubectl top nodes && kubectl top pods -A"
echo ""
echo -e "\033[36mArgoCD:\033[0m"
echo "  argocd login --core                          # no server needed"
echo "  kubectl -n argocd get app -o yaml"
echo "  argocd app list  (needs port-forward first)"
echo "  kubectl port-forward svc/argocd-server -n argocd 8080:80 &"
echo "  argocd login localhost:8080 --username admin --insecure"
echo ""
echo -e "\033[36mHelm:\033[0m"
echo "  helm list -A"
echo "  helm get values monitoring -n monitoring"
echo "  helm history monitoring -n monitoring"
echo ""
echo -e "\033[36mESO:\033[0m"
echo "  kubectl get externalsecrets -A"
echo "  kubectl get clustersecretstore"
echo "  kubectl get secret db-credentials -o jsonpath='{.data.password}' | base64 -d"
echo ""
echo -e "\033[36mPrometheus:\033[0m"
echo "  kubectl port-forward svc/monitoring-kube-prometheus-prometheus -n monitoring 9090:9090 &"
echo "  # Then open http://localhost:9090"
echo ""
echo -e "\033[36mPython k8s client:\033[0m"
echo "  export KUBECONFIG=/tmp/k3s.yaml"
echo "  python3 -c 'from kubernetes import client, config; config.load_kube_config(); print(client.CoreV1Api().list_namespace())'"
echo ""
echo -e "\033[36mWorkspace files:\033[0m"
echo "  /workspace/app.log  pod.log  access.log  values.yaml  deployment.yaml"
echo ""
